name: TabDesignPlus
main: com.example.TabDesignPlus
version: 1.0.0
api-version: 1.20
authors: [nusuntnight]
description: Handle scoreboards and tablists like a pro with this high-performance plugin.

softdepend: [PlaceholderAPI]
commands:
  tdp:
    description: Main command for TabDesignPlus
    usage: /tdp <reload|toggle|tabtoggle|bartoggle>
    aliases: [tabdesign, tdesign]
    permission: tabdesignplus.use
    permission-message: You do not have permission to use this command.

permissions:
  tabdesignplus.reload:
    description: Allows reloading the plugin by using /tdp reload
    default: op 